### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by ranjit-git** [Edu4rdSHL/unimap#12]
running unimap gives bellow error

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/resolver_engine.rs:266:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Edu4rdSHL** [comment]
Please give all possible details, which command are you running, etc.

**Comment by ranjit-git** [comment]
coomand that i used

`unimap --fast-scan -f domain_list.txt --ports $TOP_1000_PORTS -q  --url-output --threads 10`
domain_list.txt contains 130 domain

**Comment by Edu4rdSHL** [comment]
Make sure that you don't have empty lines in `domain_list.txt` and that the ports in `$TOP_1000_PORTS` are valid.

**Comment by ranjit-git** [comment]
hello @Edu4rdSHL 
i just found that scan for ```useast1.sugarcrm.com``` domain cause above error
also this domain ```prod-it-bastion-01.useast1.sugarcrm.com```

**Comment by Edu4rdSHL** [comment]
Thanks, I will investigate.

**Comment by ranjit-git** [comment]
any progress?

**Comment by Edu4rdSHL** [comment]
A quick check, returns that both domains you provided resolve to a private IP address... both resolve to 10.20.1.183...

**Comment by Edu4rdSHL** [comment]
Mmm, that shouldn't happen, we have added https://github.com/Edu4rdSHL/unimap/blob/7c6e717c0becbf17d6ef6cbc386d24ae0a6e2dfa/src/resolver_engine.rs#L224 to avoid that. Which unimap version is that? Please post the output of `unimap -V`

**Comment by ranjit-git** [comment]
my unimap version is Unimap 0.5.1

**Comment by Edu4rdSHL** [comment]
Can you try https://github.com/Edu4rdSHL/unimap/releases/tag/0.6.0 ?

**Comment by ranjit-git** [comment]
v0.6.0 also gives the same error

**Comment by ranjit-git** [comment]
any update?

getting bellow when running on latest version ```echo useast1.sugarcrm.com |RUST_BACKTRACE=1 ./unimap --fast-scan```

```
[INFO] Performing parallel resolution for 1 targets with 1 threads, it will take a while...
thread 'main' panicked at src/resolver_engine.rs:271:30:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:127:5
   3: unimap::resolver_engine::parallel_resolver_all
   4: unimap::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

**Comment by Edu4rdSHL** [comment]
It should be fixed in the latest commit. useast1.sugarcrm.com returns a private IP address, which we do not scan anyway, but the message is now clear.
